"""messages

Revision ID: bacc6c60cb03
Revises: 3750502a4779
Create Date: 2023-07-28 17:03:45.306177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacc6c60cb03'
down_revision = '3750502a4779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chats', ['id'])
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'estimates', ['id'])
    op.drop_constraint('message_chat_association_message_id_fkey', 'message_chat_association', type_='foreignkey')
    op.create_foreign_key(None, 'message_chat_association', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'photos', ['id'])
    op.create_unique_constraint(None, 'stories', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'stories', type_='unique')
    op.drop_constraint(None, 'photos', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'message_chat_association', type_='foreignkey')
    op.create_foreign_key('message_chat_association_message_id_fkey', 'message_chat_association', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'estimates', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'chats', type_='unique')
    # ### end Alembic commands ###
