"""Update_subs

Revision ID: ddf12658b573
Revises: 0063a1783f51
Create Date: 2023-07-25 22:43:49.997355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf12658b573'
down_revision = '0063a1783f51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stories', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.add_column('users', sa.Column('subscriptions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscribers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribers')
    op.drop_column('users', 'subscriptions')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'stories', type_='unique')
    # ### end Alembic commands ###
